services:
  mysql:
    image: mysql:8
    container_name: healthops_mysql
    restart: always #If your computer restarts or the MySQL process crashes, Docker will automatically try to bring the database back up.
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: